Minibus_Hire_System.web/Models/SignIn/RegistrationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Minibus_Hire_System.web.Models.SignIn
{
    public class RegistrationViewModel
    {
        [Required(ErrorMessage = "First Name is Required")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last Name is Required")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Address1 is Required")]
        [Display(Name = "Address1")]
        public string Address1 { get; set; }

        [Display(Name = "Address2")]
        public string Address2 { get; set; }

        [Display(Name = "Address3")]
        public string Address3 { get; set; }

        [Required(ErrorMessage = "City is Required")]
        [Display(Name = "City")]
        public string City { get; set; }

        [Required(ErrorMessage = "County is Required")]
        [Display(Name = "County")]
        public string County { get; set; }

        [Required(ErrorMessage = "Country is Required")]
        [Display(Name = "Country")]
        public string Country { get; set; }

        [Required(ErrorMessage = "Email is Required")]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "PhoneNumber is Required")]
        [Display(Name = "PhoneNumber")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "Password is Required")]
        [StringLength(25, ErrorMessage = "Password must me between 8 to 25 characters", MinimumLength = 8)]
        [RegularExpression("^((?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])|(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[^a-zA-Z0-9])|(?=.*?[A-Z])(?=.*?[0-9])(?=.*?[^a-zA-Z0-9])|(?=.*?[a-z])(?=.*?[0-9])(?=.*?[^a-zA-Z0-9])).{8,}$", ErrorMessage = "Passwords must be at least 8 characters and contain at 3 of 4 of the following: upper case (A-Z), lower case (a-z), number (0-9) and special character (e.g. !@#$%^&*)")]
        [DataType(dataType: DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Confirm Password is Required")]
        [DataType(dataType: DataType.Password)]
        [Compare("Password", ErrorMessage = "Confirm Password does not match with password")]
        public string ConfirmPassword { get; set; }
    }
}

Minibus_Hire_System.web/Models/SignIn/SignInViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Minibus_Hire_System.web.Models.SignIn
{
    public class SignInViewModel
    {
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Email address is required")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Display(Name = "Password")]
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

Minibus_Hire_System.web/Controllers/SignInController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Minibus_Hire_System.Interfaces;
using Minibus_Hire_System.web.Models.SignIn;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Minibus_Hire_System.web.Controllers
{
    public class SignInController : Controller
    {
        private readonly IUserService userService;

        public SignInController(IUserService _userService)
        {
            userService = _userService;
        }
        public IActionResult Index()
        {            
            return View();
        }

        //public IActionResult Registration()
        //{
        //    return View();
        //}

        [HttpPost]
        public bool Signin(SignInViewModel model)// string email, string password)
        {
            if (string.IsNullOrWhiteSpace(model.Email) || string.IsNullOrWhiteSpace(model.Password))
                return false;

            ///TODO::need to check the credential in database

            return true;
        }

        [HttpPost]
        public IActionResult Registration(RegistrationViewModel model)
        {
            if (!ModelState.IsValid)
                return RedirectToAction(nameof(Index));
                //return View(model);

            var result = userService.AddUser(new Object.UserObject
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Address1 = model.Address1,
                Address2 = model.Address2,
                Address3 = model.Address3,
                City = model.City,
                County = model.County,
                Country = model.Country,
                Email = model.Email,
                PhoneNumber = model.PhoneNumber,
            });

            if (result)
                return View();
            else
                return View(model);
        }
        
        public IList<string> ValidateRegistration(RegistrationViewModel model)
        {
            IList<string> validation = new List<string>();
            if (string.IsNullOrWhiteSpace(model.FirstName))
                validation.Add("First Name is required");
            if (string.IsNullOrWhiteSpace(model.LastName))
                validation.Add("Last Name is required");

            return validation;
        }
    }
}

Minibus_Hire_System.web/Views/SignIn/Index.cshtml
@{
    Layout = "_Layout";
}

<div class="container-fluid" style="margin-top:100px;">
    <div class="cont">
        <div class="form sign-in">
            @await Html.PartialAsync("_Signin.cshtml")
        </div>
        <div class="sub-cont">
            <div class="img">
                <div class="img__text m--up">
                    <h2>New here?</h2>
                    <p>Sign up and discover great amount of new opportunities!</p>
                </div>
                <div class="img__text m--in">
                    <h2>One of us?</h2>
                    <p>If you already has an account, just sign in. We've missed you!</p>
                </div>
                <div class="img__btn">
                    <span class="m--up">Sign Up</span>
                    <span class="m--in">Sign In</span>
                </div>
            </div>
            <div class="form sign-up">
                @await Html.PartialAsync("_Registration.cshtml")
            </div>
        </div>
    </div>
</div>



@section Styles {
    <link href="~/css/SigninStyles.css" rel="stylesheet" />
}

@section Scripts {
    <script src="~/js/SigninScript.js"></script>
    <script>
        document.querySelector('.img__btn').addEventListener('click', function () {
            document.querySelector('.cont').classList.toggle('s--signup');
        });

        function AlertFuction() {
            var emailValue = document.getElementById('email').value
            alert('Email is : ' + emailValue);
        }
    </script>
} 

Minibus_Hire_System.web/Views/SignIn/_Registration.cshtml
@model Minibus_Hire_System.web.Models.SignIn.RegistrationViewModel


<form asp-controller="SignIn" asp-action="Registration">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h3>Registration</h3>
            </div>
            <div class="col-sm-12 col-md-6">
                <button type="submit" class="submit">Sign Up</button>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <span class="label-span">First Name</span>
                <input asp-for="FirstName" />
                <span asp-validation-for="FirstName"></span>
            </div>
            <div class="col-sm-12 col-md-6">
                <span class="label-span">Last Name</span>
                <input asp-for="LastName" />
                <span asp-validation-for="LastName"></span>
            </div>
            <div class="col-sm-12 col-md-6">
                <span class="label-span">Address Line 1</span>
                <input asp-for="Address1" />
                <span asp-validation-for="Address1"></span>
            </div>
            <div class="col-sm-12 col-md-6">
                <span class="label-span">Address Line 2</span>
                <input asp-for="Address2" />
                <span asp-validation-for="Address2"></span>
            </div>
            <div class="col-sm-12 col-md-6">
                <span class="label-span">Address Line 3</span>
                <input asp-for="Address3" />
                <span asp-validation-for="Address3"></span>
            </div>
            <div class="col-sm-12 col-md-6">
                <span class="label-span">City</span>
                <input asp-for="City" />
                <span asp-validation-for="City"></span>
            </div>
            <div class="col-sm-12 col-md-6">
                <span class="label-span">County</span>
                <input asp-for="County" />
                <span asp-validation-for="County"></span>
            </div>

            <div class="col-sm-12 col-md-6">
                <span class="label-span">Country</span>
                <input asp-for="Country" />
                <span asp-validation-for="Country"></span>
            </div>
            <div class="col-sm-12 col-md-6">
                <span class="label-span">Email</span>
                <input asp-for="Email" />
                <span asp-validation-for="Email"></span>
            </div>
            <div class="col-sm-12 col-md-6">
                <span class="label-span">Phone Number</span>
                <input asp-for="PhoneNumber" />
                <span asp-validation-for="PhoneNumber"></span>
            </div>
            <div class="col-sm-12 col-md-6">
                <span class="label-span">Password</span>
                <input asp-for="Password" />
                <span asp-validation-for="Password"></span>
            </div>
            <div class="col-sm-12 col-md-6">
                <span class="label-span">Confirm Password</span>
                <input asp-for="ConfirmPassword" />
                <span asp-validation-for="ConfirmPassword"></span>
            </div>

        </div>
    </div>
</form>

Minibus_Hire_System.web/Views/SignIn/_Signin.cshtml
@model Minibus_Hire_System.web.Models.SignIn.SignInViewModel


<h2>Welcome back,</h2>
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-3"></div>
        <div class="col-sm-12 col-md-6">
            <span class="label-span">Email</span>
            <input asp-for="Email" />
            <span asp-validation-for="Email"></span>
        </div>
        <div class="col-sm-12 col-md-3"></div>
        <div class="col-sm-12 col-md-3"></div>
        <div class="col-sm-12 col-md-6">
            <span class="label-span">Password</span>
            <input asp-for="Password" />
            <span asp-validation-for="Password"></span>
        </div>
        <div class="col-sm-12 col-md-3"></div>
    </div>
    <br />
    <div class="row">
        <button type="button" onclick="SigninFunction()" class="submit">Sign In</button>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="signInValidation" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body text-center">
                <p>Invalid email address or password.</p>
            </div>
        </div>
    </div>
</div>